### PR TITLE
[DEV APPROVED] Environment & Language Selection

### PR DESCRIPTION
**Pull request by gotbadger**
While developing syndicated tools there where some issues that made QA quite difficult:

- Code changes required to change the environment QA is carried out against.
- Only possible to use the english version of tools.
- Confusion about the behaviour of tools when trying to QA directly against partner tools pages instead of using the test harness.

This PR aims to solve these issues by adding pages for each of the environments commonly used to QA work as well as staging and production. This PR also adds the ability to select the language during the QA process so translations can be checked in the same way 

**Visual Changes:**

screen shot 2017-08-29 at 14 29 29screen shot 2017-08-29 at 14 29 52

**Dev mode changes**
In development mode only the dev environment is now shown. Development mode is still set up in the same way as before via `_config.yml`
screen shot 2017-08-29 at 14 34 13

### CODE REVIEW

**Comment by jones-agyemang** [comment]
@gotbadger is there a story for this either on _TargetProcess_ or _Trello_ that I could take a look at please?

**Comment by gotbadger** [comment]
@Tr4pSt3R Trello card: https://trello.com/c/IGlOzUyA but the main driver for this is just the issues that I have explained in the PR.

**Comment by jones-agyemang** [comment]
Thanks @gotbadger !

**Comment by tomas-stefano** [comment]
I really enjoy the solution 👍 👍 But I scratch a little bit my head on the bootstrap part, but I think for test-harness it is ok!

**Comment by tomas-stefano** [comment]
Can you update the documentation here please: https://github.com/moneyadviceservice/syndication_documentation#run-test-harness-locally

**Comment by gotbadger** [comment]
@tomas-stefano will do

**Comment by margOnline** [comment]
👍

**Pull request merged**
